start:
  description: "Starts charger. Also authorizes if configured to use authorization."
  fields:
    charger_id:
      description: "The charger id"
      example: "EH123456"

stop:
  description: "Stop charger. Also deauthorizes if configured to use authorization."
  fields:
    charger_id:
      description: "The charger id"
      example: "EH123456"

pause:
  description: "Pause charger. Keeps current charge session authorized."
  fields:
    charger_id:
      description: "The charger id"
      example: "EH123456"

resume:
  description: "Resume charger. Keeps current charge session authorized."
  fields:
    charger_id:
      description: "The charger id"
      example: "EH123456"

toggle:
  description: "Toggle charger. Corresponds to pause/resume if not configured to use authorization, stop/start if configured."
  fields:
    charger_id:
      description: "The charger id"
      example: "EH123456"

start_new:
  name: "Start - New"
  description: "Start charger. Keeps current charge session authorized."
  fields:
    device_id:
      name: Target device
      description: "Select the charger to control"
      required: true
      example: "EH123456"
      selector:
        device:
          integration: "easee"
          model: "Charging Robot"

stop_new:
  name: "Stop - New"
  description: "Stop charger. Keeps current charge session authorized."
  fields:
    device_id:
      name: Target device
      description: "Select the charger to control"
      required: true
      example: "EH123456"
      selector:
        device:
          integration: "easee"
          model: "Charging Robot"

pause_new:
  name: "Pause - New"
  description: "Pause charger. Keeps current charge session authorized."
  fields:
    device_id:
      name: Target device
      description: "Select the charger to control"
      required: true
      example: "EH123456"
      selector:
        device:
          integration: "easee"
          model: "Charging Robot"

resume_new:
  name: "Resume - New"
  description: "Resume charger. Keeps current charge session authorized."
  fields:
    device_id:
      name: Target device
      description: "Select the charger to control"
      required: true
      example: "EH123456"
      selector:
        device:
          integration: "easee"
          model: "Charging Robot"

toggle_new:
  name: "Toggle - New"
  description: "Pause charger. Keeps current charge session authorized."
  fields:
    device_id:
      name: Target device
      description: "Select the charger to control"
      required: true
      example: "EH123456"
      selector:
        device:
          integration: "easee"
          model: "Charging Robot"

reboot_new:
  name: "Reboot - New"
  description: "Reboot charger"
  fields:
    device_id:
      name: Target device
      description: "Select the charger to control"
      required: true
      example: "EH123456"
      selector:
        device:
          integration: "easee"
          model: "Charging Robot"

update_firmware_new:
  name: "Update firmware - New"
  description: "Update charger firmware"
  fields:
    device_id:
      name: Target device
      description: "Select the charger to control"
      required: true
      example: "EH123456"
      selector:
        device:
          integration: "easee"
          model: "Charging Robot"

set_basic_charge_plan:
  description: "Set basic charge plan"
  fields:
    charger_id:
      description: "The charger id"
      example: "EH123456"
    start_datetime:
      description: "Plan start time"
      example: "2020-07-28T19:51"
    stop_datetime:
      description: "Plan stop time"
      example: "2020-07-28T19:51"
    repeat:
      description: "Repeat plan"
      example: True

delete_basic_charge_plan:
  description: "Delete basic charge plan"
  fields:
    charger_id:
      description: "The charger id"
      example: "EH123456"

override_schedule:
  description: "Override charger schedule and start charging"
  fields:
    charger_id:
      description: "The charger id"
      example: "EH123456"

smart_charging:
  description: "Enable/disable smart charging"
  fields:
    charger_id:
      description: "The charger id"
      example: "EH123456"
    enable:
      description: "enable"
      example: True

reboot:
  description: "Reboot charger"
  fields:
    charger_id:
      description: "The charger id"
      example: "EH123456"

update_firmware:
  description: "Update charger firmware"
  fields:
    charger_id:
      description: "The charger id"
      example: "EH123456"

set_circuit_dynamic_limit:
  description: "Set circuit dynamic limit (current available to share by all chargers on a circuit)."
  fields:
    circuit_id:
      description: "The circuit id"
      example: "11000"
    currentP1:
      description: "Phase 1 current"
      example: 10
    currentP2:
      description: "Phase 2 current (Optional)"
      example: 10
    currentP3:
      description: "Phase 3 current (Optional)"
      example: 10

set_circuit_max_limit:
  description: "Set circuit max limit. Caution! Should not be used by automation (may wear out flash memory if set too frequently)."
  fields:
    circuit_id:
      description: "The circuit id"
      example: "11000"
    currentP1:
      description: "Phase 1 current"
      example: 10
    currentP2:
      description: "Phase 2 current (Optional)"
      example: 10
    currentP3:
      description: "Phase 3 current (Optional)"
      example: 10

set_charger_circuit_dynamic_limit:
  description: "Set circuit dynamic limit (current available to share by all chargers on a circuit)."
  fields:
    charger_id:
      description: "The charger id"
      example: "EH123456"
    currentP1:
      description: "Phase 1 current"
      example: 10
    currentP2:
      description: "Phase 2 current (Optional)"
      example: 10
    currentP3:
      description: "Phase 3 current (Optional)"
      example: 10

set_charger_circuit_max_limit:
  description: "Set circuit max limit. Caution! Should not be used by automation (may wear out flash memory if set too frequently)."
  fields:
    charger_id:
      description: "The charger id"
      example: "EH123456"
    currentP1:
      description: "Phase 1 current"
      example: 10
    currentP2:
      description: "Phase 2 current (Optional)"
      example: 10
    currentP3:
      description: "Phase 3 current (Optional)"
      example: 10

set_charger_circuit_offline_limit:
  description: "Set circuit offline limit used if charger is offline (fallback). Caution! Should not be used by automation (may wear out flash memory if set too frequently)."
  fields:
    charger_id:
      description: "The charger id"
      example: "EH123456"
    currentP1:
      description: "Phase 1 current"
      example: 10
    currentP2:
      description: "Phase 2 current (Optional)"
      example: 10
    currentP3:
      description: "Phase 3 current (Optional)"
      example: 10

set_charger_dynamic_limit:
  description: "Set charger dynamic limit"
  fields:
    charger_id:
      description: "The charger id"
      example: "EH123456"
    current:
      description: "Charger current"
      example: 10


set_charger_dynamic_limit_new:
  name: "Set charger dynamic limit - New:"
  description: "Set charger dynamic limit - can be used in automations"
  fields:
    device_id:
      name: Target device
      description: "Select the charger to control"
      required: true
      example: "EH123456"
      selector:
        device:
          integration: "easee"
          model: "Charging Robot"
    current:
      name: "Current"
      required: true
      description: "Max dynamic charging current"
      example: 16
      default: 16
      selector:
        number:
          min: 0
          max: 40
          step: 1
          unit_of_measurement: "A"
          mode: slider

set_charger_max_limit:
  description: "Set charger max limit. Caution! Should not be used by automation (may wear out flash memory if set too frequently)."
  fields:
    charger_id:
      description: "The charger id"
      example: "EH123456"
    current:
      description: "Charger current"
      example: 10

set_charging_cost:
  description: "Set charging cost per kwh for charger site"
  fields:
    charger_id:
      description: "The charger id"
      example: "EH123456"
    cost_per_kwh:
      description: "Cost per kWh"
      example: 0.3
    vat:
      description: "VAT (Optional)"
      example: 25.0
    currency_id:
      description: "Currency"
      example: "EUR"

set_charger_access:
  description: "Set access level on the charger"
  fields:
    charger_id:
      description: "The charger id"
      example: "EH123456"
    access_level:
      description: "1: Open for all, 2: Require easee account, 3: whitelist"
      example: 1

set_charger_access_new:
  description: "Set access level on the charger"
  name: "Set access level on the charger - New:"
  fields:
    device_id:
      name: Target device
      description: "Select the charger to control"
      required: true
      example: "EH123456"
      selector:
        device:
          integration: "easee"
          model: "Charging Robot"
    access_level:
      name: "Access level"
      description: "Select one of the levels"
      example: 1
      required: true
      selector:
        select:
          options:
            - label: Open for all
              value: 1
            - label: Require Easee account
              value: 2
            - label: Whitelist
              value: 3
